language: node_js
node_js:
  - 14
services:
  - docker
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm install ci
script:
  - npm run test
deploy:
  provider: script
  script: . ./scripts/docker_push.sh
  on:
    branch: master