version: "3"
services:
  api:
    container_name: score-api
    env_file:
      - .env.staging
    restart: always
    build: .
    ports:
      - "8080:3004"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"